name: Terraform plan
on:
  push
env:
  AWS_REGION: "us-east-2"
permissions:
  id-token: write
  contents: read
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3

  terraform-plan:
    runs-on: ubuntu-latest
    needs: checkout
    strategy:
      matrix:
        workspace: ["workspaces/global", "workspaces/management"]
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::117936299034:role/GitHubOIDCAccess
          role-session-name: GitHub_Actions_Session
          aws-region: ${{ env.AWS_REGION }}
      - run: terraform init -chdir=${{ matrix.workspace }} -backend-config=../backend.hcl
      - run: |-
          terraform plan -chdir=${{matrix.workspace }} --no-color --input=false
      - run: |
          echo "Terraform plan :spiral_note_pad: - ${{ matrix.workspace }}" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.plan.outputs.stdout }}" >> $GITHUB_STEP_SUMMARY
